### ISSUE TITLE
Presentation should be a plain JWT if no _sd claims are present

### ISSUE THREAD

**Issue by awoie** [vcstuff/oauth-sd-jwt-vc#135]
If the SD-JWT VC contains no `_sd` claims and therefore can be represented as a plain JWT, no trailing tilde should be necessary for presentations.

**Comment by awoie** [comment]
Yes, that is the current direction but my point is that we should potentially change that. The reason is that it is awkward if developers cannot use standard JWT libs without removing the tilde first.

**Comment by paulbastian** [comment]
My points towards the current approach solving everything with SD-JWT and keeping the tilde:
- the specification is much cleaner
- I expect implementations to be much cleaner
- I don't see confusion with trailing tilde, because typ is not jwt but sd-jwt
- most interop profiles will require SD support anyway

**Comment by awoie** [comment]
@paulbastian you don't see a problem with developers not being able to use standard JWT libs for creating and verifying plain JWT VCs?
